version: "3.9"

services:
  php-cli:
    container_name: sf-messanger-php-cli
    image: sf-messanger/php-cli:dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
    depends_on:
      - rabbit-mq
  rabbit-mq:
    container_name: sf-messanger-rabbit-mq
    image: rabbitmq:3.8.9-management
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
